@echo off
cd /d "%~dp0"
echo First pdflatex run...
pdflatex -interaction=batchmode research_paper.tex
echo Running bibtex...
bibtex research_paper
echo Second pdflatex run...
pdflatex -interaction=batchmode research_paper.tex
echo Final pdflatex run...
pdflatex -interaction=nonstopmode research_paper.tex
echo Done!
